services:
    sftpgo:
        image: drakkan/sftpgo
        ports: 
            - "8080:8080"
            - "2022:2022"
            - "2121:2121"
            - "50000-50100:50000-50100"
        environment: 
            - "SFTPGO_FTPD__BINDINGS__0__PORT=2121"
            - "SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP=127.0.0.1"